name: build_ac2100
on:
  workflow_dispatch:

jobs:
  MT7621:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment.
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/prenv.sh)

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: coolsnowwolf/lede

      - name: Download and Load custom configuration
        run: |
          curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/mt7621/.config >.config
          bash <(curl -fsSL https://raw.githubusercontent.com/1orz/My-action/master/lean-lede/diy.sh)
          make defconfig

      - name: Download package
        run: |
          make download -j8

      - name: When Multi-core compile failure will be rollback to Single core compile
        run: |
          echo -e "Will be use $(nproc) thread compile"
          sudo df -h
          make -j$(nproc) || make -j1 V=sc
          sudo df -h
