name: ssh-to-action

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - name: SSH connection to Actions
        uses: 1orz/ssh-action@master

      - name: Upload Flies
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Files
          path: upload/
